#!/bin/sh

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

TMPDIR=

onexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		rm -rf $TMPDIR
	fi
}

if [ -f libjpeg-turbo-3.0.3.armel.rpm ]; then
	rm -f libjpeg-turbo-3.0.3.armel.rpm
fi

umask 022
TMPDIR=`mktemp -d /tmp/libjpeg-turbo-build.XXXXXX`

mkdir -p $TMPDIR/RPMS
ln -fs `pwd` $TMPDIR/BUILD
rpmbuild -bb --define "_blddir $TMPDIR/buildroot" --define "_topdir $TMPDIR" \
	--target armel pkgscripts/rpm.spec; \
cp $TMPDIR/RPMS/armel/libjpeg-turbo-3.0.3-20260718.armel.rpm \
	libjpeg-turbo-3.0.3.armel.rpm
