#!/bin/sh

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

TMPDIR=

onexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		rm -rf $TMPDIR
	fi
}

if [ -f libjpeg-turbo-3.0.3.arm64.rpm ]; then
	rm -f libjpeg-turbo-3.0.3.arm64.rpm
fi

umask 022
TMPDIR=`mktemp -d /tmp/libjpeg-turbo-build.XXXXXX`

mkdir -p $TMPDIR/RPMS
ln -fs `pwd` $TMPDIR/BUILD
rpmbuild -bb --define "_blddir $TMPDIR/buildroot" --define "_topdir $TMPDIR" \
	--target arm64 pkgscripts/rpm.spec; \
cp $TMPDIR/RPMS/arm64/libjpeg-turbo-3.0.3-20260718.arm64.rpm \
	libjpeg-turbo-3.0.3.arm64.rpm
